IF NOT EXISTS (SELECT name FROM master.sys.databases WHERE name = N'PayrollDB')
BEGIN
    CREATE DATABASE PayrollDB;
END
GO

USE PayrollDB;
GO

-- 1. EMPLOYEE_LOGIN
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[EMPLOYEE_LOGIN]') AND type in (N'U'))
BEGIN
CREATE TABLE EMPLOYEE_LOGIN (
    EMP_ID VARCHAR(20) PRIMARY KEY, -- Needs to be PK to be referenced
    EMP_EMAIL VARCHAR(100) UNIQUE,
    PASSWORD VARCHAR(100) NOT NULL
);
END
GO

-- 2. PROFILE
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PROFILE]') AND type in (N'U'))
BEGIN
CREATE TABLE PROFILE (
    EMP_ID VARCHAR(20) FOREIGN KEY REFERENCES EMPLOYEE_LOGIN(EMP_ID),
    EMP_NAME VARCHAR(100) NOT NULL,
    EMP_CONTACT_NUMBER VARCHAR(20),
    EMP_DOB DATE,
    EMP_GENDER VARCHAR(10),
    EMP_ADDRESS VARCHAR(255),
    EMP_DEPARTMENT VARCHAR(100),
    DATE_OF_JOIN DATE,
    LOCATION VARCHAR(100),
    BANK_NAME VARCHAR(150),
    ACCOUNT_NUMBER VARCHAR(50),
    IFSC_CODE VARCHAR(20),
    PAN VARCHAR(50),
    EMP_PROFILE_PIC VARCHAR(255),
    RESET_TOKEN VARCHAR(255),
    RESET_TOKEN_EXPIRATION DATETIME,
    CREATED_AT DATETIME DEFAULT GETDATE(),
    PROFILE_UPDATED_AT DATETIME
);
END
GO

-- 3. LEAVES_TABLE
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[LEAVES_TABLE]') AND type in (N'U'))
BEGIN
CREATE TABLE LEAVES_TABLE (
    LEAVE_ID INT IDENTITY(1,1) PRIMARY KEY,
    EMP_ID VARCHAR(20) FOREIGN KEY REFERENCES EMPLOYEE_LOGIN(EMP_ID),
    LEAVE_TYPE VARCHAR(50),
    LEAVE_START_DATE DATE,
    LEAVE_END_DATE DATE,
    REASON VARCHAR(255),
    LEAVE_STATUS VARCHAR(50),
    APPLIED_DATE DATETIME DEFAULT GETDATE()
);
END
GO

-- 4. PAYROLL
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PAYROLL]') AND type in (N'U'))
BEGIN
CREATE TABLE PAYROLL (
    PAYROLL_ID VARCHAR(20) PRIMARY KEY,
    EMP_ID VARCHAR(20) FOREIGN KEY REFERENCES EMPLOYEE_LOGIN(EMP_ID),
    EMP_NAME VARCHAR(100),
    EMP_DESIGNATION VARCHAR(100),
    EMP_SALARY DECIMAL(18,2),
    EMP_BONUS DECIMAL(18,2),
    EMP_DEDUCTIONS DECIMAL(18,2),
    EMP_NETPAY DECIMAL(18,2)
);
END
GO

-- 5. MONTHLY_PAYROLL_SUMMARY
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MONTHLY_PAYROLL_SUMMARY]') AND type in (N'U'))
BEGIN
CREATE TABLE MONTHLY_PAYROLL_SUMMARY (
    SUMMARY_ID VARCHAR(20) PRIMARY KEY,
    PAYROLL_ID VARCHAR(20), -- FOREIGN KEY REFERENCES PAYROLL(PAYROLL_ID), but sometimes independent
    TOTAL_EMPLOYEES INT,
    TOTAL_DEPARTMENTS INT,
    TOTAL_PAYROLL DECIMAL(18,2)
);
END
GO

-- 6. ACTIVITYTABLE
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ACTIVITYTABLE]') AND type in (N'U'))
BEGIN
CREATE TABLE ACTIVITYTABLE (
    ACTIVITY_ID INT IDENTITY(1,1) PRIMARY KEY,
    EMP_ID VARCHAR(20) FOREIGN KEY REFERENCES EMPLOYEE_LOGIN(EMP_ID),
    MESSAGE VARCHAR(150) NOT NULL,
    CREATEDAT DATETIME NOT NULL DEFAULT GETDATE(),
    UPDATEDAT DATETIME NOT NULL DEFAULT GETDATE()
);
END
GO

-- 7. ADMINLOGINTABLE
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ADMINLOGINTABLE]') AND type in (N'U'))
BEGIN
CREATE TABLE ADMINLOGINTABLE (
    ADMIN_EMAIL VARCHAR(100) PRIMARY KEY,
    ADMIN_PASSWORD VARCHAR(100) NOT NULL,
    CREATEDAT DATETIME NOT NULL DEFAULT GETDATE()
);
END
GO

-- 8. DEPARTMENT
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DEPARTMENT]') AND type in (N'U'))
BEGIN
CREATE TABLE DEPARTMENT (
    DEPT_NAME VARCHAR(100) PRIMARY KEY,
    EMP_ID VARCHAR(20) FOREIGN KEY REFERENCES EMPLOYEE_LOGIN(EMP_ID),
    DEPT_MANAGER VARCHAR(100) UNIQUE,
    DEPT_DESCRIPTION VARCHAR(100) NOT NULL,
    CREATEDAT DATETIME NOT NULL DEFAULT GETDATE(),
    UPDATEDAT DATETIME NULL
);
END
GO

-- 9. ONSITE_EMPLOYEE
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ONSITE_EMPLOYEE]') AND type in (N'U'))
BEGIN
CREATE TABLE ONSITE_EMPLOYEE (
    ONSITE_ID INT IDENTITY(1,1) PRIMARY KEY,
    EMP_ID VARCHAR(20), -- Can be NULL if not explicitly tied to EMPLOYEE_LOGIN
    EMP_NAME VARCHAR(100) NOT NULL,
    ROLE VARCHAR(50) NOT NULL,
    EMP_EMAIL VARCHAR(100) UNIQUE,
    LOCATION VARCHAR(50) NOT NULL,
    LOCALTIME VARCHAR(50) NOT NULL,
    CURRENCY VARCHAR(10) NOT NULL,
    EMP_STATUS VARCHAR(20) NOT NULL,
    CREATEDAT DATETIME NOT NULL DEFAULT GETDATE(),
    UPDATEDAT DATETIME NOT NULL DEFAULT GETDATE()
);
END
GO

-- 10. MONTHLY_PAYROLL
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MONTHLY_PAYROLL]') AND type in (N'U'))
BEGIN
CREATE TABLE MONTHLY_PAYROLL (
    PAYROLL_ID VARCHAR(20) PRIMARY KEY, -- If PAYROLL_ID exists in PAYROLL, maybe this should be MONTHLY_PAYROLL_ID
    MONTH VARCHAR(20) NOT NULL,
    YEAR INT NOT NULL,  -- using INT for year is safer
    CREATEDAT DATETIME NOT NULL DEFAULT GETDATE()
);
END
GO

-- Initialize Admin if empty
IF NOT EXISTS (SELECT * FROM [dbo].[ADMINLOGINTABLE] WHERE ADMIN_EMAIL = 'payrollmanagementsystem123@gmail.com')
BEGIN
    -- using 'admin123' as default password (you should hash it conceptually if your API expects hash, but the API will handle hashing. For now we will rely on API to create it or insert plain text if API checks plain text)
    -- Actually API uses bcrypt. So we don't insert here, API will insert the admin if not exists.
    PRINT 'Admin will be initialized by the backend.'
END
GO

-- 11. LOGIN_LOGS (Unified Tracking)
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[LOGIN_LOGS]') AND type in (N'U'))
BEGIN
CREATE TABLE LOGIN_LOGS (
    LOG_ID INT IDENTITY(1,1) PRIMARY KEY,
    USER_ID VARCHAR(100) NOT NULL, -- Admin Email or Emp ID
    ROLE VARCHAR(20) NOT NULL,     -- ADMIN or EMPLOYEE
    LOGIN_TIME DATETIME DEFAULT GETDATE()
);
END
GO
